-- phpMyAdmin SQL Dump
-- version 4.5.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 2019-01-17 05:25:20
-- 服务器版本： 5.7.11
-- PHP Version: 5.6.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `phpcmsv9`
--

-- --------------------------------------------------------

--
-- 表的结构 `zy_zyconfig`
--
CREATE TABLE IF NOT EXISTS `zy_zyconfig` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `config_name` varchar(255) NOT NULL COMMENT '配置名称',
  `model_name` varchar(255) NOT NULL COMMENT '所需模块',
  `item_name` varchar(255) NOT NULL COMMENT '模块项目名',
  `url` varchar(255) NOT NULL COMMENT '地址',
  `api_url` varchar(255) NOT NULL COMMENT 'API地址',
  `explain` text NOT NULL COMMENT '说明',
  `api_explain` text NOT NULL COMMENT 'api说明',
  `key` VARCHAR(255) NOT NULL COMMENT '配置表的关键字',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=24 ;

DELETE FROM zy_zyconfig WHERE `item_name`='zymessagesys';
INSERT INTO `zy_zyconfig` (`config_name`, `model_name`, `item_name`, `url`, `api_url`, `explain`, `api_explain`, `key`) VALUES
('获取会员组用户', 'zymember 会员系统', 'zymessagesys', 'localhost/zm/index.php?m=zymember&c=zymember_api&a=zymessagesys_group', '域名/index.php?m=zymember&c=zymember_api&a=zymessagesys_group', '一、应用模块：通讯模块      配置来源：会员模块\r\n\r\n二、用途：获取会员组用户\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n    groupid（*会员组id，默认是0=全部会员) \r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  post', '一、请求参数：\r\n\r\n\r\n\r\n 1）请求参数说明：\r\n\r\n    groupid（*会员组id，默认是0=全部会员) \r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http post\r\n\r\n\r\n\r\n\r\n\r\n二、返回信息 :\r\n\r\n\r\n\r\n  返回格式：{"status":"success","code":200,"message":"操作成功","data":[{"userid":"1","username":"yyy","nickname":"123发的说法","mobile":"15067614058","groupid":"18"},{"userid":"3","username":"a1WLhFL6","nickname":"测试12","mobile":"15067610000","groupid":"18"},{"userid":"6","username":"jw6cSQC4","nickname":"15067614057","mobile":"15067614052","groupid":"2"}]}\r\n\r\n\r\n\r\n\r\n\r\n三、返回字段解释：\r\n\r\n\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n  data: 提示信息\r\n  data.userid: 用户id\r\n  data.username: 用户帐号\r\n  data.nickname: 用户昵称\r\n  data.mobile: 用户手机号码\r\n  data.groupid: 用户组id\r\n\r\n\r\n\r\n四、状态信息说明：\r\n\r\n\r\n\r\n 200：操作成功\r\n\r\n\r\n\r\n\r\n五、实例代码：\r\n\r\n\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zymember&c=zymember_api&a=zymessagesys_group'',\r\n\r\n  data:{groupid:1},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''post'',\r\n\r\n  success:function(res){\r\n\r\n   {"status":"success","code":200,"message":"操作成功","data":[{"userid":"1","username":"yyy","nickname":"123发的说法","mobile":"15067614058","groupid":"18"},{"userid":"3","username":"a1WLhFL6","nickname":"测试12","mobile":"15067610000","groupid":"18"},{"userid":"6","username":"jw6cSQC4","nickname":"15067614057","mobile":"15067614052","groupid":"2"}]}\r\n\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zymessagesys8'),
('公共_发送短信验证码消息', 'zymessagesys 通讯系统', 'zymessagesys', 'localhost/zm/index.php?m=zymessagesys&c=messagesys_api&a=pub_sendsms', '域名/index.php?m=zymessagesys&c=messagesys_api&a=pub_sendsms', '一、应用模块：通讯模块      配置来源：通讯模块\r\n\r\n二、用途：公共_发送短信验证码消息\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n    mobile（*手机号码)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  post', '一、请求参数：\r\n\r\n\r\n\r\n 1）请求参数说明：\r\n\r\n    mobile（*手机号码)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http post\r\n\r\n\r\n\r\n\r\n\r\n二、返回信息 :\r\n\r\n\r\n\r\n  返回格式：{''status''=>''error/success'',''code''=>''200'',''message''=>''操作成功''}\r\n\r\n\r\n\r\n\r\n\r\n三、返回字段解释：\r\n\r\n\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n\r\n\r\n\r\n\r\n\r\n四、状态信息说明：\r\n\r\n\r\n\r\n 200：操作成功\r\n\r\n -1：请设置短信配置信息\r\n\r\n -2：手机号码不能为空\r\n\r\n -3：手机号格式错误\r\n\r\n -4：当日发送短信数量超过限制 20 条\r\n\r\n -5：同一IP 24小时允许请求的最大数\r\n\r\n -100：短信发送失败\r\n\r\n\r\n\r\n\r\n五、实例代码：\r\n\r\n\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zymessagesys&c=messagesys_api&a=pub_sendsms'',\r\n\r\n  data:{mobile:15067614058},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''post'',\r\n\r\n  success:function(res){\r\n\r\n   {''status''=>''error/success'',''code''=>''200'',''message''=>''操作成功''}\r\n\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zymessagesys1'),
('公共_短信_清空当前账号验证码', 'zymessagesys 通讯系统', 'zymessagesys', 'localhost/zm/index.php?m=zymessagesys&c=messagesys_api&a=pub_sms_clear', '域名/index.php?m=zymessagesys&c=messagesys_api&a=pub_sms_clear', '一、应用模块：通讯模块      配置来源：通讯模块\r\n\r\n二、用途：公共_短信_清空当前账号验证码\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n    mobile（*手机号码)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  post', '一、请求参数：\r\n\r\n\r\n\r\n 1）请求参数说明：\r\n\r\n    mobile（*手机号码)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http post\r\n\r\n\r\n\r\n\r\n\r\n二、返回信息 :\r\n\r\n\r\n\r\n  返回格式：{''status''=>''error/success'',''code''=>''200'',''message''=>''操作成功''}\r\n\r\n\r\n\r\n\r\n\r\n三、返回字段解释：\r\n\r\n\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n\r\n\r\n\r\n\r\n\r\n四、状态信息说明：\r\n\r\n\r\n\r\n 200：操作成功\r\n\r\n\r\n\r\n\r\n五、实例代码：\r\n\r\n\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zymessagesys&c=messagesys_api&a=pub_sms_clear'',\r\n\r\n  data:{mobile:15067614058},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''post'',\r\n\r\n  success:function(res){\r\n\r\n   {''status''=>''error/success'',''code''=>''200'',''message''=>''操作成功''}\r\n\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zymessagesys5'),
('前台_消息列表', 'zymessagesys 通讯系统', 'zymessagesys', 'localhost/zm/index.php?m=zymessagesys&c=api&a=message_list', '域名/index.php?m=zymessagesys&c=api&a=message_list', '一、应用模块：通讯模块      配置来源：通讯模块\r\n\r\n二、用途：前台-消息列表\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n    userid（*用户id)  page（当前页码，默认第一页)  pagesize（当前的条数，默认20条)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  post', '一、请求参数：\r\n\r\n\r\n\r\n 1）请求参数说明：\r\n\r\n    userid（*用户id)  page（当前页码，默认第一页)  pagesize（当前的条数，默认20条)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http post\r\n\r\n\r\n\r\n\r\n\r\n二、返回信息 :\r\n\r\n\r\n\r\n  返回格式：{"status":"success","code":200,"message":"登录成功","data":[{"title":"123发呆","content":"123123范德萨发","thumb":"http://localhost/pub/statics/zymessagesys/images/message_icon.png","sendname":"系统消息","time":"1906/05/13"},{"title":"阿发地方","content":"1防守打法法撒旦法撒旦法啊当发呆发","thumb":"http://localhost/pub/statics/zymessagesys/images/message_icon.png","sendname":"系统消息","time":"1906/05/13"}],"page":{"pagesize":"2","totalpage":1,"totalnum":"2"}}\r\n\r\n\r\n\r\n\r\n\r\n三、返回字段解释：\r\n\r\n\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n  data: 数据组\r\n\r\n    data.title: 标题\r\n    data.content: 内容\r\n    data.thumb: 缩略图\r\n    data.sendname: 发件人\r\n    data.time: 发送时间\r\n\r\n  page: 页码数据组\r\n\r\n    page.pagesize:  每页10条\r\n    page.totalpage: 总页数\r\n    page.totalnum:  总条数\r\n\r\n\r\n\r\n\r\n四、状态信息说明：\r\n\r\n\r\n\r\n 200：操作成功\r\n -1：用户id不能为空\r\n\r\n\r\n\r\n\r\n五、实例代码：\r\n\r\n\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zymessagesys&c=api&a=message_list'',\r\n\r\n  data:{userid:1},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''post'',\r\n\r\n  success:function(res){\r\n\r\n   {"status":"success","code":200,"message":"登录成功","data":[{"title":"123发呆","content":"123123范德萨发","thumb":"http://localhost/pub/statics/zymessagesys/images/message_icon.png","sendname":"系统消息","time":"1906/05/13"},{"title":"阿发地方","content":"1防守打法法撒旦法撒旦法啊当发呆发","thumb":"http://localhost/pub/statics/zymessagesys/images/message_icon.png","sendname":"系统消息","time":"1906/05/13"}],"page":{"pagesize":"2","totalpage":1,"totalnum":"2"}}\r\n\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zymessagesys6'),
('前台_消息内容页', 'zymessagesys 通讯系统', 'zymessagesys', 'localhost/zm/index.php?m=zymessagesys&c=api&a=message_show', '域名/index.php?m=zymessagesys&c=api&a=message_show', '一、应用模块：通讯模块      配置来源：通讯模块\r\n\r\n二、用途：前台-消息内容页\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n    userid（*用户id)  showid（*消息id)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  post', '一、请求参数：\r\n\r\n\r\n\r\n 1）请求参数说明：\r\n\r\n    userid（*用户id) showid（*消息内容id)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http post\r\n\r\n\r\n\r\n\r\n\r\n二、返回信息 :\r\n\r\n\r\n\r\n  返回格式：{"status":"success","code":200,"message":"操作成功","data":{"title":"阿发地方","content":"1防守打法法撒旦法撒旦法啊当发呆发","url":"大沙发的","sendname":"系统消息","data":"32351451345"}}\r\n\r\n\r\n\r\n\r\n\r\n三、返回字段解释：\r\n\r\n\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n  data: 数据组\r\n\r\n    data.title: 标题\r\n    data.content: 内容\r\n    data.thumb: 缩略图\r\n    data.sendname: 发件人\r\n    data.time: 发送时间\r\n\r\n\r\n\r\n四、状态信息说明：\r\n\r\n\r\n\r\n 200：操作成功\r\n -1：用户id、内容id不能为空\r\n\r\n\r\n\r\n\r\n五、实例代码：\r\n\r\n\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zymessagesys&c=api&a=message_show'',\r\n\r\n  data:{userid:1,showid:1},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''post'',\r\n\r\n  success:function(res){\r\n\r\n   {"status":"success","code":200,"message":"操作成功","data":{"title":"阿发地方","content":"1防守打法法撒旦法撒旦法啊当发呆发","url":"大沙发的","sendname":"系统消息","data":"32351451345"}}\r\n\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zymessagesys7'),
('公共_短信_验证验证码是否正确', 'zymessagesys 通讯系统', 'zymessagesys', 'localhost/zm/index.php?m=zymessagesys&c=messagesys_api&a=pub_sms_verify', '域名/index.php?m=zymessagesys&c=messagesys_api&a=pub_sms_verify', '一、应用模块：通讯模块      配置来源：通讯模块\r\n\r\n二、用途：公共_短信_验证验证码是否正确\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n    mobile（*手机号码)    verify_code（*短信验证码)    clear（*清空当前账号验证码：否=1，是=2)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  post', '一、请求参数：\r\n\r\n\r\n\r\n 1）请求参数说明：\r\n\r\n    mobile（*手机号码)    verify_code（*短信验证码)    clear（*清空当前账号验证码：否=1，是=2)\r\n    \r\n 2）返回格式： json\r\n\r\n 3）请求方式： http post\r\n\r\n\r\n\r\n\r\n\r\n二、返回信息 :\r\n\r\n\r\n\r\n  返回格式：{''status''=>''error/success'',''code''=>''200'',''message''=>''操作成功''}\r\n\r\n\r\n\r\n\r\n\r\n三、返回字段解释：\r\n\r\n\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n\r\n\r\n\r\n\r\n\r\n四、状态信息说明：\r\n\r\n\r\n 200：操作成功\r\n -1：手机号码、验证码不能为空\r\n -2：验证码错误\r\n -3：验证码超时\r\n\r\n\r\n\r\n\r\n五、实例代码：\r\n\r\n\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zymessagesys&c=messagesys_api&a=pub_sms_verify'',\r\n\r\n  data:{mobile:15067614058,verify_code:123123,clear:1},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''post'',\r\n\r\n  success:function(res){\r\n\r\n   {''status''=>''error/success'',''code''=>''200'',''message''=>''操作成功''}\r\n\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zymessagesys4'),
('公共_发送系统消息', 'zymessagesys 通讯系统', 'zymessagesys', 'localhost/zm/index.php?m=zymessagesys&c=messagesys_api&a=pub_sendsy', '域名/index.php?m=zymessagesys&c=messagesys_api&a=pub_sendsy', '一、应用模块：公共模块      配置来源：通讯模块\r\n\r\n二、用途：公共_发送系统消息\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n      userid（*会员ID)  content(*内容)  title(*标题)  sendname(*发件人：暂时填写=系统消息)  url(外部连接)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  post\r\n\r\n\r\n\r\n\r\n  ', '一、请求参数：\r\n\r\n\r\n\r\n 1）请求参数说明：\r\n\r\n    userid（*会员ID)  content(*内容)  title(*标题)  sendname(*发件人：暂时填写=系统消息)  url(外部连接)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http post\r\n\r\n\r\n\r\n\r\n\r\n二、返回信息 :\r\n\r\n\r\n\r\n  返回格式：{ "status": "success", "code": 200, "message": "发送成功" }\r\n\r\n\r\n\r\n\r\n\r\n三、返回字段解释：\r\n\r\n\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n\r\n\r\n四、状态信息说明：\r\n\r\n\r\n\r\n 200：操作成功\r\n -1：请输入用户id\r\n -2：用户不存在\r\n -3：数据不能为空\r\n\r\n\r\n\r\n\r\n五、实例代码：\r\n\r\n\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zymessagesys&c=messagesys_api&a=pub_sendsy'',\r\n\r\n  data:{userid:1,showid:1},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''post'',\r\n\r\n  success:function(res){\r\n\r\n   { "status": "success", "code": 200, "message": "发送成功" }\r\n\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zymessagesys2'),
('公共_发送邮件消息', 'zymessagesys 通讯系统', 'zymessagesys', 'localhost/zm/index.php?m=zymessagesys&c=messagesys_api&a=pub_sendemail', '域名/index.php?m=zymessagesys&c=messagesys_api&a=pub_sendemail', '一、应用模块：通讯模块      配置来源：通讯模块\r\n\r\n二、用途：公共_发送邮件消息\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n    title（*发送标题)    content（*发送内容)    address（*接收人邮箱)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  post', '一、请求参数：\r\n\r\n\r\n\r\n 1）请求参数说明：\r\n\r\n    title（*发送标题)    content（*发送内容)    address（*接收人邮箱)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http post\r\n\r\n\r\n\r\n\r\n\r\n二、返回信息 :\r\n\r\n\r\n\r\n  返回格式：{ "status": "success", "code": 200, "message": "发送成功" }\r\n\r\n\r\n\r\n\r\n\r\n三、返回字段解释：\r\n\r\n\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n\r\n\r\n四、状态信息说明：\r\n\r\n\r\n\r\n 200：操作成功\r\n -1：标题、内容、接收人邮箱不能为空\r\n -2：请去通讯模块进行配置\r\n\r\n\r\n\r\n\r\n五、实例代码：\r\n\r\n\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zymessagesys&c=messagesys_api&a=pub_sendemail'',\r\n\r\n  data:{title:1,content:1,address:5828720@qq.com},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''post'',\r\n\r\n  success:function(res){\r\n\r\n   { "status": "success", "code": 200, "message": "发送成功" }\r\n\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zymessagesys3');
